import {loadTimeData} from '//resources/js/load_time_data.js';
loadTimeData.data = {
    "addLinkTitle": "Add shortcut",
    "audioError": "Please check your microphone.",
    "backButton": "Back",
    "backgroundColor": "#353535",
    "backgroundImageUrl": "chrome-untrusted://new-tab-page/custom_background_image?url=https%3A%2F%2Flh6.googleusercontent.com%2Fproxy%2FMdXBfxi4vCF0ZKalCD1XFNnrumrgr3DoIIwdqaPlZG9Q0K4hUVQQUGfBnqzm3-jY1EJEREorVqCj7TUKyEqhPiz32FyE051g9G8sMKhGdyM%3Dw3840-h2160-p-k-no-nd-mv",
    "backgroundsMenuItem": "Background",
    "cancelButton": "Cancel",
    "chromeRefresh2023Attribute": "",
    "close": "Close",
    "colorPickerLabel": "Custom color",
    "controlledSettingPolicy": "This setting is managed by your administrator.",
    "copyLink": "Copy Link",
    "customBackgroundDisabled": "Custom backgrounds have been turned off by your administrator",
    "customBackgroundDisabledByPolicy": false,
    "customizeButton": "Customize Chrome",
    "customizeCards": "Customize cards",
    "customizeChromeEnabled": false,
    "customizeThisPage": "Customize this page",
    "defaultThemeLabel": "Default color",
    "details": "Details",
    "disableModuleToastMessage": "You won't see $1 on this page again",
    "disableQuestsModuleToastMessage": "You won't see $1 again",
    "disableQuestsModuleToastName": "this type of card",
    "dismissModuleToastMessage": "$1 hidden",
    "doneButton": "Done",
    "doodleLink": "Doodle Link",
    "editLinkTitle": "Edit shortcut",
    "email": "E-mail",
    "facebook": "Facebook",
    "fontfamily": "'Segoe UI', Tahoma, sans-serif",
    "fontfamilyMd": "'Segoe UI', Tahoma, sans-serif",
    "fontsize": "75%",
    "googleBaseUrl": "https://www.google.com/",
    "handleMostVisitedNavigationExplicitly": true,
    "hideAllCards": "Hide all cards",
    "hideShortcuts": "Hide shortcuts",
    "hideShortcutsDesc": "Don't show shortcuts on this page",
    "hideSuggestions": "Hide suggestions",
    "historyClustersImagesEnabled": true,
    "historyClustersModuleEnabled": true,
    "historyClustersModuleLoadEnabled": false,
    "historyClustersSuggestionChipHeaderEnabled": false,
    "invalidUrl": "Type a valid URL",
    "language": "en",
    "languageError": "Voice search in your language is not available.",
    "learnMore": "Learn more",
    "learnMoreA11yLabel": "Learn more about using a microphone",
    "lensSearchButtonLabel": "Search by image",
    "lensSearchUploadDialogCloseButtonLabel": "Close",
    "lensSearchUploadDialogDragDropTitle": "Drop an image here",
    "lensSearchUploadDialogDragTitle": "Drag an image here or",
    "lensSearchUploadDialogErrorFileSize": "Can't upload. Use an image smaller than 20MB.",
    "lensSearchUploadDialogErrorFileType": "Can't upload. Use an image in one of these formats: .jpg, .gif, .png, .bmp, .tif, or .webp",
    "lensSearchUploadDialogErrorMultipleFiles": "Can't search multiple images. Add one image at a time.",
    "lensSearchUploadDialogErrorMultipleUrls": "Can't search multiple images. Add one image at a time.",
    "lensSearchUploadDialogLoadingText": "Uploading…",
    "lensSearchUploadDialogOfflineButtonLabel": "Try again",
    "lensSearchUploadDialogOfflineSubtitleText": "Check your internet connection and try again",
    "lensSearchUploadDialogOfflineText": "No network connection",
    "lensSearchUploadDialogOrText": "OR",
    "lensSearchUploadDialogSearchButtonLabel": "Search",
    "lensSearchUploadDialogTextPlaceholder": "Paste image link",
    "lensSearchUploadDialogTitle": "Search any image with Google Lens",
    "lensSearchUploadDialogUploadFileTitle": "upload a file",
    "lensSearchUploadDialogValidationErrorConformance": "Can't use this link. Check for typos or use another link to try again.",
    "lensSearchUploadDialogValidationErrorScheme": "Can't use this link. Check that your link starts with 'http://' or 'https://' to try again.",
    "linkAddedMsg": "Shortcut added",
    "linkCancel": "Cancel",
    "linkCantCreate": "Can't create shortcut",
    "linkCantEdit": "Can't edit shortcut",
    "linkDone": "Done",
    "linkEditedMsg": "Shortcut edited",
    "linkRemove": "Remove",
    "linkRemovedMsg": "Shortcut removed",
    "listening": "Listening…",
    "logoEnabled": true,
    "middleSlotPromoDismissalEnabled": true,
    "middleSlotPromoEnabled": true,
    "moduleInfoButtonTitle": "About this card",
    "moduleRecipeExtendedExperimentEnabled": false,
    "modulesCartCartMenuHideMerchant": "Hide $1",
    "modulesCartCartMenuHideMerchantToastMessage": "$1 hidden. You'll see it again when you revisit your cart.",
    "modulesCartCartMenuRemoveMerchant": "Never show $1",
    "modulesCartCartMenuRemoveMerchantToastMessage": "You won't see $1 again",
    "modulesCartConsentStepOneButton": "Continue",
    "modulesCartConsentStepOneOneMerchantContent": "Get discounts for $1",
    "modulesCartConsentStepOneThreeMerchantsContent": "Get discounts for $1, $2 and more",
    "modulesCartConsentStepOneTwoMerchantsContent": "Get discounts for $1 and $2",
    "modulesCartConsentStepTwoContent": "Let Google use your cart to find available discounts?",
    "modulesCartConsentStepTwoDifferentColor": false,
    "modulesCartDiscountChipAmount": "$1 off",
    "modulesCartDiscountChipUpToAmount": "Up to $1 off",
    "modulesCartDiscountConentTitle": "Get discounts?",
    "modulesCartDiscountConsentAccept": "Get discounts",
    "modulesCartDiscountConsentAcceptConfirmation": "If Google finds a discount, you will see it on this page",
    "modulesCartDiscountConsentConfirmationDismiss": "Got it",
    "modulesCartDiscountConsentContent": "Let Chrome find personalized discounts on your carts?",
    "modulesCartDiscountConsentContentV3": "Let Google use your cart to find available discounts?",
    "modulesCartDiscountConsentReject": "No thanks",
    "modulesCartDiscountConsentRejectConfirmation": "Discounts are off. You can turn them on in the customize menu",
    "modulesCartDiscountConsentVariation": 4,
    "modulesCartDiscountInlineCardShowCloseButton": true,
    "modulesCartInfo": "You’re seeing carts that help you easily get back to items you left in shopping carts across the web.\n        \u003Cbr>\n        \u003Cbr>\n        You can manage settings from the card menu or see more options in Customize Chrome.",
    "modulesCartItemCountMultiple": "$1 items",
    "modulesCartItemCountSingular": "$1 item",
    "modulesCartLower": "carts",
    "modulesCartLowerThese": "these carts",
    "modulesCartLowerYour": "your carts",
    "modulesCartModuleMenuHideToastMessage": "Carts hidden. They'll reappear when you make changes.",
    "modulesCartSentence": "Your carts",
    "modulesCartSentenceV2": "In your shopping cart",
    "modulesCartStepOneStaticContent": "Let Google help you find discounts for your carts",
    "modulesCartStepOneUseStaticContent": true,
    "modulesCartWarmWelcome": "Find what you added to shopping carts and check out when you're ready",
    "modulesChromeCartInHistoryClustersModuleEnabled": true,
    "modulesCustomizeButtonText": "Customize cards",
    "modulesDisableButtonText": "Never show $1",
    "modulesDisableButtonTextV2": "Don't show $1",
    "modulesDismissButtonText": "Hide $1",
    "modulesDragAndDropEnabled": false,
    "modulesDriveFilesLower": "these files",
    "modulesDriveFilesSentence": "Files",
    "modulesDriveInfo": "You’re seeing suggested files to help you easily get back to your most recent activity in Google Drive.\n        \u003Cbr>\n        \u003Cbr>\n        You can manage settings from the card menu or see more options in Customize Chrome.",
    "modulesDriveSentence": "Google Drive files",
    "modulesDriveSentence2": "Drive files",
    "modulesDriveTitle": "From your Google Drive",
    "modulesDriveTitleV2": "From Your Drive",
    "modulesDummyLower": "this module",
    "modulesDummyTitle": "Super Duper Module",
    "modulesEnabled": true,
    "modulesFeedTitle": "Following",
    "modulesFirstRunExperienceBodyLine1": "Pick cards that keep you updated on things that matter to you",
    "modulesFirstRunExperienceBodyLine2": "See all card options in \u003Ca is=\"action-link\" id=\"customizeChromeLink\" tabIndex=0 on-click=\"onCustomizeModuleFre_\">Customize Chrome\u003C/a>",
    "modulesFirstRunExperienceEnabled": false,
    "modulesFirstRunExperienceOptIn": "Got it",
    "modulesFirstRunExperienceOptOut": "Don't show",
    "modulesFirstRunExperienceOptOutToast": "You won't see cards on this page again",
    "modulesFirstRunExperienceTitle": "Your page, your way",
    "modulesHeaderIconEnabled": true,
    "modulesJourneyDisable": "this card",
    "modulesJourneysBookmarked": "Bookmarked",
    "modulesJourneysCartAnnotation": "In your cart",
    "modulesJourneysCartTileLabelDefault": "Items in your cart $1 from $2, $3, viewed $4",
    "modulesJourneysCartTileLabelPlural": "$1 items in your cart $2 from $3, $4, viewed $5",
    "modulesJourneysCartTileLabelSingular": "1 item in your cart $1 from $2, $3, viewed $4",
    "modulesJourneysDismissButton": "No longer interested",
    "modulesJourneysDoneButton": "Mark as done and hide",
    "modulesJourneysInfo": "You’re seeing pages you've visited and suggested searches to help you easily get back to your most recent activity.\n        \u003Cbr>\n        \u003Cbr>\n        You can manage settings from the card menu or see more options in Customize Chrome.",
    "modulesJourneysOpenAllInNewTabGroupButtonText": "Open all in new tab group",
    "modulesJourneysResumeJourney": "Resume browsing for $1",
    "modulesJourneysSearchSuggAcc": "Search for $1",
    "modulesJourneysShowAll": "Show all",
    "modulesJourneysShowAllAcc": "Show all searches for $1",
    "modulesJourneysShowAllButton": "Open in side panel",
    "modulesKaleidoscopeTitle": "Top picks for you",
    "modulesLoadEnabled": false,
    "modulesLoadTimeout": 3000,
    "modulesMenuItem": "Cards",
    "modulesMoreActions": "More actions for $1",
    "modulesNewTagLabel": "New",
    "modulesOverflowScrollbarEnabled": true,
    "modulesPhotosInfo": "You’re seeing photo and video highlights from your Google Photos library. You can control what shows up in your highlights at \u003Ca href=\"https://photos.google.com/settings?referrer=CHROME_NTP\" target=\"_blank\">photos.google.com/settings\u003C/a>.\n        \u003Cbr>\n        \u003Cbr>\n        You can manage settings for this card from the card menu or see more options in Customize Chrome.",
    "modulesPhotosMemoriesBaloonIllustrationTitle": "Your trip",
    "modulesPhotosMemoriesDisable": "memories",
    "modulesPhotosMemoriesDisabled": "memories from Google Photos",
    "modulesPhotosMemoriesExplore": "Explore more of your memories in Google Photos",
    "modulesPhotosMemoriesHiddenToday": "Memories hidden for today",
    "modulesPhotosMemoriesHideToday": "your memories for today",
    "modulesPhotosMemoriesSoftOptOut": "Memories hidden for two days",
    "modulesPhotosMemoriesWelcomeButtonOptIn": "See memories",
    "modulesPhotosMemoriesWelcomeButtonOptOut": "No thanks",
    "modulesPhotosMemoriesWelcomeButtonSoftOptOut": "Ask me later",
    "modulesPhotosMemoriesWelcomeExample": "2 years ago",
    "modulesPhotosMemoriesWelcomeText": "Start exploring your memories from Google Photos, whenever you’re signed in.",
    "modulesPhotosMemoriesWelcomeTitle": "See your memories here",
    "modulesPhotosNew": "New",
    "modulesPhotosSentence": "Google Photos memories",
    "modulesPhotosTitle": "From your Google Photos",
    "modulesRecipeExtendedInfo": "You’re seeing recipes based on your recent Search activity for recipes.\n        \u003Cbr>\n        \u003Cbr>\n        You can manage settings from the card menu or see more options in Customize Chrome.",
    "modulesRecipeHistoricalExperimentEnabled": false,
    "modulesRecipeInfo": "You’re seeing suggested recipes based on your recent Search activity for recipes.\n        \u003Cbr>\n        \u003Cbr>\n        You can manage settings from the card menu or see more options in Customize Chrome.",
    "modulesRecipeTasksLower": "recipe ideas",
    "modulesRecipeTasksLowerThese": "these recipe ideas",
    "modulesRecipeTasksSentence": "Recipe ideas",
    "modulesRecipeViewedTasksLower": "recently viewed recipes",
    "modulesRecipeViewedTasksLowerThese": "these recently viewed recipes",
    "modulesRecipeViewedTasksSentence": "Recently viewed recipes",
    "modulesRedesignedEnabled": false,
    "modulesTasksInfo": "You're seeing this item based on your previous activity using Google services. You can see your data, delete it, and change your settings at \u003Ca href=\"https://myactivity.google.com/\" target=\"_blank\">myactivity.google.com\u003C/a>.\n        \u003Cbr>\n        \u003Cbr>\n        Learn about the data Google collects and why at \u003Ca href=\"https://policies.google.com/\" target=\"_blank\">policies.google.com\u003C/a>.",
    "modulesTasksInfoClose": "Close",
    "modulesTasksInfoTitle": "About this card",
    "modulesVisibleManagedByPolicy": false,
    "mostVisited": "Most visited sites",
    "mostVisitedReflowOnOverflowEnabled": true,
    "myShortcuts": "My shortcuts",
    "nameField": "Name",
    "navigationStartTime": 1.695750733556905e+12,
    "networkError": "No Internet connection.",
    "noBackground": "Default Chrome",
    "noTranslation": "Didn't get that.",
    "noVoice": "Please check your microphone and audio levels.",
    "ok": "OK",
    "oneGoogleBarEnabled": true,
    "otherError": "Unknown error.",
    "permissionError": "Voice search has been turned off.",
    "photosModuleCustomArtWork": "",
    "photosModuleSplitSvgCustomArtWork": false,
    "prerenderEnabled": false,
    "prerenderStartTimeThreshold": 300,
    "realboxDefaultIcon": "//resources/images/icon_search.svg",
    "realboxIsTall": false,
    "realboxLensDirectUpload": false,
    "realboxLensSearch": true,
    "realboxLensVariations": "CIm2yQEIpbbJAQipncoBCN-HywEIkqHLAQib_swBCIWgzQEI_LHNAQjcvc0BCN_EzQEIt8XNAQjoxc0BCLnKzQEItsvNAQjU0M0BCMfRzQEIkdLNAQi61M0BCMnWzQEI19fNAQj5wNQVGI_OzQEYutLNARjrjaUX",
    "realboxMatchSearchboxTheme": false,
    "realboxSeparator": " - ",
    "realboxWidthBehavior": "",
    "reducedLogoSpaceEnabled": true,
    "refreshDaily": "Refresh daily",
    "removeScrim": true,
    "removeSuggestion": "Remove suggestion",
    "restoreDefaultLinks": "Restore default shortcuts",
    "restoreThumbnailsShort": "Restore all",
    "ruleBasedDiscountEnabled": false,
    "searchBoxHint": "Search Google or type a URL",
    "shareDoodle": "Share Doodle",
    "shortcutAlreadyExists": "Shortcut already exists",
    "shortcutMoreActions": "More actions for $1 shortcut",
    "shortcutsCurated": "Shortcuts are curated by you",
    "shortcutsEnabled": true,
    "shortcutsMenuItem": "Shortcuts",
    "shortcutsOption": "Shortcuts",
    "shortcutsSuggested": "Shortcuts are suggested based on websites you visit often",
    "showCartInQuestModuleSetting": true,
    "showSuggestions": "Show suggestions",
    "singleRowShortcutsEnabled": true,
    "speak": "Speak now",
    "textdirection": "ltr",
    "themeCreatedBy": "Theme created by",
    "themeManagedDialogBody": "Your administrator has set a default theme which cannot be changed.",
    "themeManagedDialogTitle": "Theme is set by your Organization",
    "themesContainerLabel": "Pick a theme color",
    "themesMenuItem": "Color and theme",
    "thirdPartyThemeDescription": "Current theme you have installed",
    "title": "New Tab",
    "tryAgain": "Try again",
    "twitter": "Twitter",
    "undo": "Undo",
    "undoDescription": "Press Ctrl+Z to undo",
    "undoDismissPromoButtonToast": "You won't see this specific message again",
    "uninstallThirdPartyThemeButton": "Uninstall",
    "uploadFromDevice": "Upload from device",
    "urlField": "URL",
    "voiceSearchButtonLabel": "Search by voice",
    "waiting": "Waiting…",
    "webstoreThemesToastButtonText": "Find themes",
    "webstoreThemesToastMessage": "You can find older colors in the Chrome Web Store",
    "wideModulesEnabled": true
};